//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public System.DateTime Invoice_Date { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Taxes { get; set; }
        public Nullable<double> Net { get; set; }
    }
}
